### ISSUE TITLE
missing controls attr in video

### ISSUE THREAD

**Issue by mananamenos** [lumihq/purescript-react-basic-dom#1]
Hi, I've noticed that `video` does not include `controls` attribute in `Generated.purs`. It should be somewhere here: https://github.com/lumihq/purescript-react-basic-dom/blob/main/src/React/Basic/DOM/Generated.purs#L17352

**Comment by mananamenos** [comment]
Hi @spicydonuts, any news on this issue? Why doesn't `controls` attribute get generated (i could not figured that out looking at the project's source)? In the meanwhile, i suppose i should clone the project and just add the `controls` attribute by hand.
Thanks

**Comment by spicydonuts** [comment]
Sorry, I looked at it briefly while refactoring things but I haven't figured it out yet. Hopefully I can get to it later this week.

**Comment by spicydonuts** [comment]
@mananamenos I think I found the issue. Does this PR look right to you?

**Comment by mananamenos** [comment]
Hi @spicydonuts, i should have seen this. Thank you!
