### ISSUE TITLE
`renderToString` is missing

### ISSUE THREAD

**Issue by paluh** [lumihq/purescript-react-basic-dom#10]
Could you please tell me if I can open a PR with simple binding for `renderToString` (something simple like [here](https://github.com/rowtype-yoga/ry-starter-spa/blob/main/ui-server/src/Main.purs#L26))?

**Comment by spicydonuts** [comment]
It was actually just added in #6, but I haven't released a new version yet. You can reference `main` to try it, and I'll try to get it tagged soon.

**Comment by spicydonuts** [comment]
Released as `v3.1.0`
