### ISSUE TITLE
`dataTransfer` HTML docs

### ISSUE THREAD

**Issue by jamesdbrock** [lumihq/purescript-react-basic-dom#18]
The `dataTransfer` function is not included in the generated docs on Pursuit. I don't know why.

https://github.com/lumihq/purescript-react-basic-dom/blob/cb761db2ea6722c793f74757333893ff558a7bf0/src/React/Basic/DOM/Events.purs#L44

https://pursuit.purescript.org/packages/purescript-react-basic-dom/3.2.0/docs/React.Basic.DOM.Events

**Comment by ptrfrncsmrph** [comment]
This seems to be resolved with latest version of docs https://pursuit.purescript.org/packages/purescript-react-basic-dom/4.2.0/docs/React.Basic.DOM.Events#v:dataTransfer

**Comment by jamesdbrock** [comment]
Yup
