### ISSUE TITLE
Bug with Anonymous and Forward Ref

### ISSUE THREAD

**Issue by ghivert** [lumihq/purescript-react-basic-dom#2]
Hi!

I was building an input text with React Basic 15 (and Basic Hooks 6), and just figured out I’m losing focus everytime I type in the input. I didn’t modified things.

I looked up a little bit more to know why. A tour in the React devtools explained a lot of things:

With React Basic 14.
![Before](https://user-images.githubusercontent.com/7314118/86249424-944d8280-bbaf-11ea-8c75-1067183f1101.PNG)

With React Basic 15.
![After](https://user-images.githubusercontent.com/7314118/86249488-a62f2580-bbaf-11ea-8069-9da0402b5e02.PNG)

We can see, with the exact same code, that a lot of Anonymous just appeared. I think the main change come from [here](https://github.com/lumihq/purescript-react-basic-dom/blob/16f2912491bc3daa99309e914912c8c1b414d986/src/React/Basic/DOM/Internal.js#L8). But on this point, I’m really not sure of what’s happening, but I think the `React.forwardRef` just generates a new `Anonymous` component. Each render, it generates a new input component, and it replaces the old input.

**Comment by spicydonuts** [comment]
It definitely shouldn't on each render, and the number there seems excessive 🤔 I'll take a look

**Comment by spicydonuts** [comment]
@ghivert Can you try installing the `fix-forwardref` branch? I tried a simple example and can't reproduce the loss of focus, but that branch should pre-apply `unsafeCreateDOMComponent` to avoid calling `React.forwardRef` during render. Tbh I don't really understand why I'm not able to reproduce it.

**Comment by spicydonuts** [comment]
I was able to reproduce this in lumi-components and `fix-forwardref` does fix it there, at least where `unsafeCreateDOMComponent` is applied outside of a render function. This is kind of expected, as the function does create a component function now, vs before when it just `unsafeCoerce`'d a string. This still doesn't seem like an ideal fix though. For one, there are those wrapper components for each element which is noisy (though `fix-fowardref` does fix its name so they don't all say "Anonymous" now). Second, it's hard to find everywhere that will break because of this change because `unsafeCreateDOMComponent` became effectful without its type changing. I see two options:

1. Keep the implementation as it is in `fix-forwardref` and change `unsafeCreateDOMComponent :: String -> ReactComponent props` to `unsafeCreateDOMComponent :: String -> Effect (ReactComponent props)`. This is more correct given the current implementation and will highlight anywhere this function is used incorrectly.
1. Alternatively, monkey-patch `React.createElement` instead and move the `data-`/`aria-` implementation there. This seems kind of gross and possibly problematic in the future, but it would allow `unsafeCreateDOMComponent` to return to its original implementation of unsafeCoercing strings.

**Comment by spicydonuts** [comment]
3. I could remove the `_data` and `_aria` props from the `ReactComponent` definitions in `React.Basic.DOM.Generated`, (like `a'` or `input'`) and only include them in the `props -> JSX` helpers.. (like `a` or `input`). That would break some use cases for those props, but wouldn't require monkey-patching React or changing how `unsafeCreateDOMComponent` works. 🤔 For example, you'd no longer be able to use `_data` or `_aria` with `react-basic-emotion` elements.

**Comment by spicydonuts** [comment]
I released option #1 as `react-basic-dom` `v2.0.0`. If this doesn't solve the problem or you want to discuss those wrapper elements more you can keep replying here and I'll reopen the issue.

**Comment by ghivert** [comment]
1. To begin, I tried the v2.0.0 and it fixes the problem, so thanks! I’m almost sure that the current implementation, as an effectful function, should remains as it is. Because of the nature of `unsafeCreateDOMComponent`, it should be an effect, and this will reduce the bugs encountered by users, even if they now have to use `unsafePerformEffect` a bunch of times if they want to restore the old behavior. It’s really clean and it’s the same logic as any other `Component` or `ReactComponent` we create: they’re effects.

2. I’m really against monkey-patching. It’s the best way to get unmaintainable codebases, and it requires a lot of modifications if ever React changes how it behaves.

3. I spent some time reading the code to get the big picture. I see your point about `_data` and `_aria`. I can’t figure out if moving them to helpers functions would be so much dramatic. To me, it’s clearly not dramatic, because I’m using helpers everytime, but I’m probably not representative of all developers. But couldn’t we move all the logic in the [`element` function](https://github.com/lumihq/purescript-react-basic/blob/d8087ade742a7070e35bbd999f45e373551c716d/src/React/Basic.js#L12)? I feel like it’s harmless, and could be an elegant way to deal with data and aria. Like this:

```javascript
const flattenDataProp = (props) => {
  var data = null;
  if (props._data != null) {
    data = { _data: undefined };
    Object.entries(props._data).forEach(function (entry) {
      data["data-" + entry[0]] = entry[1];
    });
  }
  var aria = null;
  if (props._aria != null) {
    aria = { _aria: undefined };
    Object.entries(props._aria).forEach(function (entry) {
      aria["aria-" + entry[0]] = entry[1];
    });
  }
  return Object.assign({}, props, data, aria);
};

exports.element = (component) => (_props) => {
  const props = flattenDataProp(_props)
  return Array.isArray(props.children)
    ? createElement.apply(null, [component, props].concat(props.children))
    : createElement(component, props);
}
```
---

Just a quick word about wrapping components. Now I get a Components explorer like this:

![Now](https://user-images.githubusercontent.com/7314118/86333879-ccef6980-bc4c-11ea-80a8-4aa4a4b4ca9e.PNG)

Do you think we can get rid of all those forwardRef for DOM nodes ? What bother me is that ref in components should be handled in a specific way: we need to pass it to underlying HTML. With DOM nodes it’s just a question of setting a ref, but for components, we need to use a forwardRef, get the ref in the child component and re-set the ref on the desired DOM child. Couldn’t we do a smarter thing for refs? Maybe something like this to begin:

```javascript
exports.unsafeCreateDOMComponent_ = (createElement) => (el) => () => {
  if (typeof el === 'string') {
    return createElement(el);
  } else {
    const c = React.forwardRef((props, ref) =>
      createElement(el)(flattenDataProp(props, ref));
    return c;
  }
};
```

This way, if `el` is not a DOM node, we continue to pass the forward ref and ensure in all cases that we can send a working ref, but in other cases, where we don’t need it, because we’re just using a plain `a` for example, we don’t see it anymore in the explorer.

Or maybe we can have a `componentRef`, just like we have an `elementKeyed`? That would force users to use ref when they need them on a particular basis and not anytime (because we’re not using them so much in React?).

**Comment by spicydonuts** [comment]
> I’m really against monkey-patching

Yeah, same, definitely want to avoid if possible.

---

> couldn’t we move all the logic in the element function?

It actually used to be there, but now that `element` lives in `react-basic` and this attribute behavior is a specific detail about how `react-dom`'s `render` function handles strings-as-react-components, so it seemed out of place there.

---

> Do you think we can get rid of all those forwardRef for DOM nodes ?

I think you've got this bit backwards. The ref forwarding is specifically for string dom nodes, so you can treat all the components in `React.Basic.DOM.Generated` as though they were plain dom nodes without the ref forwarding wrapper. The wrapper also can't know whether there are props it needs to translate until render time, at which point the wrapper component needs to already exist (or you get the bug you ran into yesterday), so it can't conditionally short circuit and avoid the wrapper.

---

> Because of the nature of unsafeCreateDOMComponent, it should be an effect

It wasn't an effect back when it was just `unsafeCoerce :: String -> ReactComponent`, but it is now with the forwardref wrapper element.

---

Here are two other alternatives, though I don't think the forwardref wrappers are so bad:

1. Remove `element` from `react-basic` and require env libraries like `react-basic-dom` and `react-basic-native` to implement their own `element` functions. I don't like this for a few reasons:
    - breaks "platform agnostic" components, for example putting all components that touch dom elements or css in a separate folder and "business" built on this layer could theoretically work with react native later without changes (because they're now tied to the dom library)
    - another major version change that will be tedious to update in large projects
1. Keep the `react-basic` version of `element` for `ReactComponent` types, but introduce a new component type in `react-basic-dom` such as `DOMReactComponent` and add `domElement :: DOMReactComponent props -> props -> JSX` which handles these special props
    - also probably a painful update, though not as bad since it wouldn't change the `props -> JSX` helpers
    - would require `react-basic-emotion` changes as well
1. Remove the `_data` and `_aria` props from all the dom components, then add a `domElement :: ReactComponent props -> props -> { _data, _aria } -> JSX` function to `react-basic-dom`
    - also requires `react-basic-emotion` changes
    - a major version change, but probably not a very painful update for most people

Option 3 is probably the best of these, but I'm not sure it's better than the current forwardref wrapper.
